In [1]:
import numpy as np

In [5]:
l=[[23,45],[67,89],[54,56]]
a2=np.array(l)

In [13]:
print(a2.ndim)
print(a2.shape)
print(a2.size)
print(a2.itemsize)
print(a2.dtype)
print(a2.size*a2.itemsize)

2
(3, 2)
6
4
int32
24


In [19]:
for i in a2:
    print(i)
 

[23 45]
[67 89]
[54 56]


In [18]:
type(i)

numpy.ndarray

## initializing arrays
- np.ones
- np.zeros
- np.eye
- np.diag


In [27]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [25]:
np.ones((3,4),dtype=np.int8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [29]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [33]:
np.zeros((2,2),dtype=bool)

array([[False, False],
       [False, False]])

In [39]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.full((3,2),2)

array([[2, 2],
       [2, 2],
       [2, 2]])

In [43]:
np.diag((5,3),2)

array([[0, 0, 5, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [45]:
np.diag((5,3,4))

array([[5, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [48]:
print(np.arange(10))
print(np.arange(2,10))
print(np.arange(2,10,2))
print(np.arange(2,10,0.5))

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6 8]
[2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [51]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [54]:
print(np.linspace(5,10,2))
print(np.linspace(5,10,3))
print(np.linspace(5,10,4))

[ 5. 10.]
[ 5.   7.5 10. ]
[ 5.          6.66666667  8.33333333 10.        ]


## basic math operations 

In [57]:
a = np.array([1,2,3])
b = np.array([1,2,3])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]
[1 1 1]
[0 0 0]
[ 1  4 27]


In [58]:
a+[1]

array([2, 3, 4])

In [61]:
a+[1,2,3]

array([2, 4, 6])

In [67]:
b1 = np.full((3,4,2),2)
b2=1
b3=np.array([2,3])
b4=np.array([[1],[1]])
print(b3.shape,b4.shape)
b3+b4

(2,) (2, 1)


array([[3, 4],
       [3, 4]])

In [83]:
a= np.arange(25)
print(a[:2])
print(a[::2])
print(a)
print(a[:-2])
print(a[5:])
print(a[-3:])
print(a[2:24:5])
print(a[[2,5,3,4]])

[0 1]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[22 23 24]
[ 2  7 12 17 22]
[2 5 3 4]


In [93]:
np.random.randint(1,2,(5,5))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [94]:
np.random.random(2)

array([0.22615752, 0.59155199])

In [121]:
np.random.normal(2)

1.9148203368382073

In [122]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

In [123]:
help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [124]:
a1=np.array([10,20,30,40,50])
np.min(a1)

10

In [126]:
np.sum(a1)

150

In [128]:
np.max(a1)

50

In [129]:
np.mean(a1)

30.0

In [130]:
np.median(a1)

30.0

In [137]:
np.quantile(a1,0.25)

20.0

In [138]:
np.quantile(a1,0.5)

30.0

In [141]:
np.quantile(a1,0.75)

40.0

In [163]:
a1=np.array([[1,2],[1,2]])
c1=np.sum(a1,axis=1)
print(np.sum(a1,axis=1))
print(np.shape(c1))
print(np.sum(a1,axis=0))

[3 3]
(2,)
[2 4]


In [165]:
b=np.sum(a1,axis=1,keepdims=True)
np.shape(b)

(2, 1)

In [171]:
def addk(a,b):
    
    ''' tha hfgyfgtbnmsnfjsmbegjs vhjgsb '''
    return a+b

In [172]:
help(addk)

Help on function addk in module __main__:

addk(a, b)
    tha hfgyfgtbnmsnfjsmbegjs vhjgsb



In [173]:
help

Type help() for interactive help, or help(object) for help about object.

In [3]:
import jag
jag.name

'jagan'

In [8]:
if '':
    print("jagan")
else:
    print("pora")

pora


In [12]:
bool('')

False

In [14]:
bool(' ')

True

In [18]:
l={1:2,2:2,3:3}
print(l.items())
print([i**0.5 for i in l])

dict_items([(1, 2), (2, 2), (3, 3)])
[1.0, 1.4142135623730951, 1.7320508075688772]
